// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoyceasx7WD31kFmZx4Cx12DnKuQKeL0U',
    appId: '1:225186221765:web:1e033b7be640a19afa6aac',
    messagingSenderId: '225186221765',
    projectId: 'smpd-fee-mate',
    authDomain: 'smpd-fee-mate.firebaseapp.com',
    storageBucket: 'smpd-fee-mate.firebasestorage.app',
    measurementId: 'G-4PG949FPD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuQ_xgxsCFrwKKT7ZQFTVYv7q_9gMr7Hg',
    appId: '1:225186221765:android:9580c0e1163bcb08fa6aac',
    messagingSenderId: '225186221765',
    projectId: 'smpd-fee-mate',
    storageBucket: 'smpd-fee-mate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH_700GleHsQWE4mUomsIuASkLDqwU4Zk',
    appId: '1:225186221765:ios:b7140791990d5618fa6aac',
    messagingSenderId: '225186221765',
    projectId: 'smpd-fee-mate',
    storageBucket: 'smpd-fee-mate.firebasestorage.app',
    iosBundleId: 'com.smpdynamics.feemate',
  );
}
